### PR TITLE
fix circuitbreaker

### LINKED ISSUE #162: 支持spring cloud hoxton插件，接入所有SCT的服务治理功能
**What is the feature you want to add?**

**Why do you want to add this feature?**

**How to implement this feature?**

**Additional context**

### PR DESCRIPTION
**Pull request by fredrikliu**
**Please provide issue(s) of this PR:**
Fixes #162

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Docs
- [ ] Discovery
- [ ] Route
- [ ] RateLimit
- [x] CircuitBreaker
- [ ] Test and Release

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any user-facing changes. This may include API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

File: polaris-agent-plugins/spring-cloud-plugins/spring-cloud-hoxton-plugin/src/main/java/cn/polarismesh/agent/plugin/spring/cloud/inject/CircuitBreakerBeanInjector.java [hunk 1]
```diff
@@ -39,18 +44,38 @@ public void onApplicationStartup(Object configurationParser, Constructor<?> conf
...
+                Thread.currentThread().getContextClassLoader())) {
+            if (null != ClassUtils.getClazz("org.springframework.cloud.openfeign.FeignClientFactoryBean",
+                    Thread.currentThread().getContextClassLoader())) {
+                Object polarisCircuitBreakerFeignClientAutoConfiguration = ReflectionUtils.invokeConstructor(configClassCreator, PolarisCircuitBreakerFeignClientAutoConfiguration.class, "polarisCircuitBreakerFeignClientAutoConfiguration");
+                ReflectionUtils.invokeMethod(processConfigurationClass, configurationParser, polarisCircuitBreakerFeignClientAutoConfiguration, Constant.DEFAULT_EXCLUSION_FILTER);
+                registry.registerBeanDefinition("polarisCircuitBreakerFeignClientAutoConfiguration", BeanDefinitionBuilder.genericBeanDefinition(
+                        PolarisCircuitBreakerFeignClientAutoConfiguration.class).getBeanDefinition());
+            }
+        }
+        if (null != ClassUtils.getClazz("org.springframework.web.reactive.DispatcherHandler",
```
Comment (andrewshan) [inline polaris-agent-plugins/spring-cloud-plugins/spring-cloud-hoxton-plugin/src/main/java/cn/polarismesh/agent/plugin/spring/cloud/inject/CircuitBreakerBeanInjector.java:57]: 在一个if分支里面判断，不要搞太多层级

**Review by andrewshan — APPROVED** [review]
