### PR TITLE
fix:fix log framework conflict.

### LINKED ISSUE #205: 1.7.0-RC7 版本的 javaagent 与主应用内的 log4j2 冲突

### PR DESCRIPTION
**Pull request by SkyeBeFreeman**
**Please provide issue(s) of this PR:**
Fixes #205 

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Docs
- [ ] Discovery
- [ ] Route
- [ ] RateLimit
- [ ] CircuitBreaker
- [ ] Test and Release

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any user-facing changes. This may include API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

File: polaris-agent-plugins/spring-cloud-plugins/spring-cloud-2022-plugin/src/main/java/cn/polarismesh/agent/plugin/spring/cloud/interceptor/SpringFactoriesLoaderInterceptor.java [hunk 1]
```diff
@@ -55,38 +54,33 @@ public SpringFactoriesLoaderInterceptor() {
     @SuppressWarnings("unchecked")
     @Override
     public void after(Object target, Object[] args, Object result, Throwable throwable) {
-        if (args[0] == null) {
-            return;
+        Map<String, List<String>> oldFactories = (Map<String, List<String>>) ReflectionUtils.getObjectByFieldName(target, "factories");
```
Comment (andrewshan) [inline polaris-agent-plugins/spring-cloud-plugins/spring-cloud-2022-plugin/src/main/java/cn/polarismesh/agent/plugin/spring/cloud/interceptor/SpringFactoriesLoaderInterceptor.java:57]: oldFactories反射取出来的，看看是否需要进行判空处理？

Comment (SkyeBeFreeman) [reply polaris-agent-plugins/spring-cloud-plugins/spring-cloud-2022-plugin/src/main/java/cn/polarismesh/agent/plugin/spring/cloud/interceptor/SpringFactoriesLoaderInterceptor.java:57]: 已修正

**Review by andrewshan — APPROVED** [review]
LGTM
